# =================================================================
# CẤU HÌNH HUGO TOÀN CỤC (GLOBAL HUGO CONFIGURATION)
# =================================================================
baseURL = "https://oaiba.github.io/dev/"
title = "Bob's Unreal Engine DevLog"
theme = ["PaperMod", "hugo-shortcodes"]
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[pagination]
pagerSize = 5

# =================================================================
# CẤU HÌNH THEME (THEME PARAMS)
# =================================================================
[params]
env = "production"
author = "Bob Pham"
description = "A deep-dive Dev Blog on Unreal Engine C++ and Blueprint, sharing knowledge, experience, and game development tutorials."
keywords = ["Unreal Engine", "C++", "Blueprint", "Game Development", "Dev Blog", "Tutorials"]
defaultTheme = "auto"
hideFooter = false
displayFullLangName = true
ShowReadingTime = true
ShowWordCount = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
ShowAllPagesInArchive = true
ShowPageNums = true

[[params.socialIcons]]
name = "github"
title = "View on GitHub"
url = "https://github.com/oaiba"
[[params.socialIcons]]
name = "linkedin"
title = "Connect on LinkedIn"
url = "https://www.linkedin.com/in/your-linkedin-id/"
[[params.socialIcons]]
name = "twitter"
title = "Follow on X"
url = "https://twitter.com/your-twitter-handle"

# =================================================================
# CẤU HÌNH ĐA NGÔN NGỮ (LANGUAGES)
# =================================================================
[languages]
# --- English ---
[languages.en]
languageName = "English"
weight = 1
title = "Bob Pham's DevLog"
contentDir = "content/en"

[languages.en.params.homeInfoParams]
Title = "Welcome to Bob Pham's DevLog!"
Content = """
      👋 I'm Bob Pham, a programmer and Unreal Engine enthusiast.
      This is where I share in-depth knowledge, experience, and practical guides
      on C++ and Blueprint, helping you unlock the full potential of Unreal Engine
      to build amazing games and interactive applications.

      Let's explore the vast world of Unreal Engine together!
      """

[languages.en.menu]
[[languages.en.menu.main]]
name = "About Me"
url = "about/"
weight = 1
[[languages.en.menu.main]]
name = "Resume"
url = "resume/"
weight = 2
[[languages.en.menu.main]]
name = "Posts"
url = "posts/"
weight = 3

# --- Vietnamese ---
[languages.vi]
languageName = "Tiếng Việt"
weight = 2
title = "Nhật ký phát triển của Bob Phạm"
contentDir = "content/vi"

[languages.vi.params.homeInfoParams]
Title = "Chào mừng đến DevLog của Bob Phạm!"
Content = """
      👋 Xin chào, mình là Bob Phạm – một lập trình viên đam mê Unreal Engine.
      Blog này chia sẻ kiến thức chuyên sâu, kinh nghiệm và hướng dẫn thực tiễn
      về lập trình C++ và Blueprint, giúp bạn khai thác tối đa Unreal Engine
      để phát triển game và ứng dụng tương tác chất lượng.

      Cùng khám phá thế giới Unreal Engine nhé!
      """

[languages.vi.menu]
[[languages.vi.menu.main]]
name = "Giới Thiệu"
url = "about/"
weight = 1
[[languages.vi.menu.main]]
name = "Hồ Sơ Năng Lực"
url = "resume/"
weight = 2
[[languages.vi.menu.main]]
name = "Bài Viết"
url = "posts/"
weight = 3

# =================================================================
# CÁC CẤU HÌNH KHÁC (OTHER CONFIGURATIONS)
# =================================================================
[assets]
favicon = "favicon.ico"
favicon16x16 = "favicon.ico"
favicon32x32 = "favicon.ico"
apple_touch_icon = "favicon.ico"

[cover]
linkFullImages = true
responsiveImages = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true